### PR TITLE
typo: "pecification" to "specification"

### PR DESCRIPTION
**Pull request by ajschumacher**

### CODE REVIEW

**Comment by jeffreyhorner** [comment]
Thanks!

**Comment by ajschumacher** [comment]
Thank you! Can I ask you also - is it possible to make a web server in R that both accepts POSTs and serves websockets? On the same endpoint?

I want to accept data in the POST body and pass it to everything listening to the websocket, on `/data`, for example. Like this: https://github.com/ajschumacher/gogd/blob/master/src/gogd/core.clj but want to see if I can do it all in R too.

I see there's a `websockets` package, but it doesn't do POST, it seems. And `Rook` doesn't do websockets, right?

I just tweeted at Yihui too: https://twitter.com/planarrowspace/status/555474095002112001 Trying to figure this out~ Thanks!

**Comment by jeffreyhorner** [comment]
Hmm... I don't know. Possible projects to research are shiny server and httpuv from RStudio.

**Comment by ajschumacher** [comment]
Thanks - looks like I will have to figure out httpuv ><

**Pull request merged**
